micronaut:
    application:
        name: server1
    server:
        port: 8082

eureka:
    client:
        registration:
            enabled: true
        defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"