micronaut:
    application:
        name: client
    server:
        port: 8081

eureka:
    client:
        registration:
            enabled: true
        defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"